name: Verify Commits
# Requires "Allow edits and access to secrets by maintainers" checked on PR
#
# - References
#   - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
#   - https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
#
# yamllint disable-line rule:line-length
# gh act -s GITHUB_TOKEN="$(gh auth token)" -P ubuntu-latest=ubuntu:22-04 --job test -W .github/workflows/ci.yml

on:
  pull_request_target:
    branches:
    - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    # NOTE(security) __base/ contains the defender controlled policy + keys
    - uses: actions/checkout@v2
      with:
        path: '__base'

    - runs: |
        cat "__base/.tools/open-architecture/governance/branches/${GITHUB_BASE_REF}/policies/upstream.yml" | yq '.data.owners[] | .keys[]' | tee public_keys.pgp

    - name: Verify Commit Signatures
      uses: publicdomainrelay/verify-mod-owner@main
      with:
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs
        base_branch: '${{ github.base_ref }}'
        # NOTE(security) This is the attacker controlled policy
        file_path: '.tools/open-architecture/governance/branches/${{ github.base_ref }}/'
        public_key_files: |
          public_keys.pgp
